### ISSUE TITLE
Initial example

### ISSUE THREAD

**Issue by mktitan** [sureshchahal/ng2-adal-examples#1]
Hi @sureshchahal 

I'm very interested in trying your [ng2-adal](https://www.npmjs.com/package/ng2-adal) and would appreciate an example.

Thank you

**Comment by sureshchahal** [comment]
I should be able to provide this after Nov 1. Meanwhile, example is very similar to https://github.com/alenny/angular2-adal-example

if you want you can use same example, just replace angular2-adal with ng2-adal.

My package is forked and enhancement of what @alenny have already done

**Comment by sureshchahal** [comment]
I am working on example and should be able to provide that by next Monday,
i.e. 10/31

**Comment by mktitan** [comment]
Sounds great, I'll be looking forward to it

**Comment by isaacrlevin** [comment]
Looks like you committed some unmerged files

**Comment by MikeLallemont** [comment]
Suresh, I need an example of using authHttp. I assume it is just subclassing http but I am getting a server error and cannot figure out why. The URL works in Postman with the credentials I'm using to get data. Here is what I am doing:

```
  constructor(
    public http: AuthHttp,
    public util: UtilProvider
  ) {
    this.dataStore = { projects: [] };
    this.projects = new Observable(observer => this.projectsObserver = observer).share();
    this.projectsObserver = <BehaviorSubject<Project[]>>new BehaviorSubject(this.dataStore.projects);
  }

  loadAll() {
    const loading = this.util.getLoading({ content: 'Loading projects, please wait...' });
    loading.present();
    // make api call
    this.http.get(this.dataUrl)
      .map(response => <Project[]>response.json())
      .subscribe(data => {
        data.forEach(p => this.dataStore.projects.push(new Project℗))
        this.projectsObserver.next(this.dataStore.projects);
      },
      error => {
        loading.dismiss();
        this.displayError('Server Error: Could not load projects.');
      },
      () => loading.dismiss()
      );
  }

```

**Comment by sureshchahal** [comment]
@MikeLallemont 
Is this url just backened service hosted in same domain as your UI application? if not, then you need to specify it in your adalConfig . In example below, specify endpoint that is different domain but use same identity  in "APIUsingSameAzureAD "

import {Injectable} from '@angular/core';

@Injectable()
export class SecretService {
    public get adalConfig(): any {

```
    var APIUsingSameAzureAD = {

    }
    return {
        tenant: '*****.onmicrosoft.com',
        clientId: '*****',
        redirectUri: window.location.origin + '/',
        postLogoutRedirectUri: window.location.origin + '/',
        endpoints: APIUsingSameAzureAD
    };
}
```

}

**Comment by MikeLallemont** [comment]
Thank you, I’m sure that will help.

**Comment by MikeLallemont** [comment]
Hey inside that APIUsingSameAzureAD object what should it look like? Is it an array or comma delimited string or what? Can I get an example? Does it include the full URL with protocol?

Thanks,
Mike

**Comment by sureshchahal** [comment]
it should be like

var endpoints = {
        "https://yourhost/api": "b6a68585-5287-45b2-ba82-383ba1f60932",
    };

**Comment by MikeLallemont** [comment]
Suresh,

We have senior consultants right now in a room trying to debug ng2-adal to be able to work with Ionic. Can you respond? We can help you fix this problem but we need to ask a couple of questions. 

Thanks,
Mike

**Comment by sureshchahal** [comment]
Sure Mike.

**Comment by sureshchahal** [comment]
Hi Mike
I called the number and left voice message. I can answer questions here or
give me a call back

Thanks

**Comment by mktitan** [comment]
@sureshchahal Thank you for the example. I'll close the issue.

**Comment by ranveeraggarwal** [comment]
Hello, for future references, I have an example here: https://github.com/ranveeraggarwal/ng2-adal-QuickStart
This is based on hours of going through all these repositories and this one completely works out of the box. @sureshchahal can you update your repo with this? Or add a link from your repo to this?

**Comment by sureshchahal** [comment]
@ranveeraggarwal Thanks for contribution. I have updated the repo with your link?
